class_name EnemyDirectionalData
extends RefCounted
## GENERATED by art/prepare_enemy_directional.py - do not edit by hand.
## Enemies with an eight-direction sheet, and each direction's charge-pose
## weapon tip in texels from the foot-line centre (columns S, SW, W, NW, N, NE, E, SE).
const TIPS := {
	"thug": [Vector2(9, -33), Vector2(4, -33), Vector2(9, -33), Vector2(8, -31), Vector2(-1, -32), Vector2(-8, -32), Vector2(-9, -33), Vector2(-4, -32)],
	"crossbow": [Vector2(0, -12), Vector2(-15, -13), Vector2(-13, -13), Vector2(-14, -16), Vector2(0, -12), Vector2(14, -16), Vector2(13, -13), Vector2(15, -13)],
	"slug": [Vector2(9, -10), Vector2(8, -9), Vector2(2, -14), Vector2(-8, -12), Vector2(-10, -9), Vector2(8, -12), Vector2(-2, -14), Vector2(-8, -9)],
	"brawler": [Vector2(-3, -26), Vector2(10, -22), Vector2(-6, -24), Vector2(-5, -24), Vector2(3, -23), Vector2(5, -25), Vector2(6, -24), Vector2(2, -25)],
	"crossbow_leader": [Vector2(0, -12), Vector2(-14, -10), Vector2(-15, -10), Vector2(-14, -11), Vector2(0, -12), Vector2(13, -12), Vector2(15, -10), Vector2(14, -11)],
	"ice_warrior": [Vector2(-6, -37), Vector2(-11, -36), Vector2(7, -37), Vector2(7, -37), Vector2(1, -37), Vector2(-9, -37), Vector2(-7, -37), Vector2(8, -36)],
	"ice_hunter": [Vector2(0, -12), Vector2(-12, -14), Vector2(-17, -16), Vector2(-17, -18), Vector2(0, -12), Vector2(16, -18), Vector2(17, -16), Vector2(12, -12)],
}
## Enemies with an eight-direction walk sheet (4 frames per direction).
const WALK := ["thug", "crossbow", "slug", "brawler", "crossbow_leader", "ice_warrior", "ice_hunter"]
