class_name PlaceholderTones
## PLACEHOLDER audio, synthesised in code until the final OGGs exist (the course .gitignore keeps
## WAV files out of the repo, so placeholders are not files). Each event gets a clearly different
## shape so they can be told apart by ear. Not generated by a model; not for the final slice.

const RATE := 22050

static var _cache := {}   # built once per run, reused across scene reloads


static func for_event(id: String) -> AudioStreamWAV:
	if not _cache.has(id):
		_cache[id] = _build(id)
	return _cache[id]


static func _build(id: String) -> AudioStreamWAV:
	match id:
		"SFX-CAST":       # 0.30 s: noise whoosh with a rising tone
			return _make(0.30, func(t: float, d: float) -> float:
				var env := _env(t, d, 0.01)
				return env * (0.45 * _noise() + 0.35 * sin(TAU * (500.0 + 900.0 * t / d) * t)))
		"SFX-WOLF-DOWN":  # 0.45 s: falling yelp, then a low thud
			return _make(0.45, func(t: float, d: float) -> float:
				if t < 0.22:
					return _env(t, 0.22, 0.005) * 0.5 * sin(TAU * (700.0 - 1200.0 * t) * t)
				var u := t - 0.22
				return _env(u, d - 0.22, 0.003) * 0.7 * sin(TAU * 70.0 * u) * exp(-u * 12.0))
		"SFX-HURT":       # 0.20 s: short low thump with grit
			return _make(0.20, func(t: float, d: float) -> float:
				return _env(t, d, 0.003) * (0.6 * signf(sin(TAU * 140.0 * t)) * exp(-t * 18.0) + 0.2 * _noise()))
		"SFX-FAIL":       # 0.90 s: descending tone fading out (shorter than the 1.2 s reload)
			return _make(0.90, func(t: float, d: float) -> float:
				return _env(t, d, 0.02) * 0.5 * sin(TAU * (440.0 - 300.0 * t / d) * t))
		"SFX-CLEAR":      # 1.20 s: rising four-note chime
			return _make(1.20, func(t: float, d: float) -> float:
				var notes := [523.25, 659.25, 783.99, 1046.5]
				var i := mini(int(t / 0.25), 3)
				var u := t - i * 0.25
				return _env(t, d, 0.01) * 0.4 * sin(TAU * notes[i] * u) * exp(-u * 3.0))
	return null


## 4.0 s placeholder music loop: a low drone and a soft pulse, built from whole cycles so the
## loop seam is clean by construction.
static func music_loop() -> AudioStreamWAV:
	if _cache.has("MUS-LOOP"):
		return _cache["MUS-LOOP"]
	var s := _make(4.0, func(t: float, _d: float) -> float:
		var drone := 0.18 * sin(TAU * 55.0 * t) + 0.10 * sin(TAU * 82.5 * t)
		var beat := fmod(t, 1.0)
		var pulse := 0.20 * sin(TAU * 110.0 * t) * exp(-beat * 6.0)
		return drone + pulse)
	s.loop_mode = AudioStreamWAV.LOOP_FORWARD
	s.loop_begin = 0
	s.loop_end = int(4.0 * RATE)
	_cache["MUS-LOOP"] = s
	return s


static func _make(seconds: float, f: Callable) -> AudioStreamWAV:
	var n := int(seconds * RATE)
	var data := PackedByteArray()
	data.resize(n * 2)
	for i in n:
		var t := float(i) / RATE
		var v := clampf(f.call(t, seconds), -1.0, 1.0)
		data.encode_s16(i * 2, int(v * 32767.0))
	var s := AudioStreamWAV.new()
	s.format = AudioStreamWAV.FORMAT_16_BITS
	s.mix_rate = RATE
	s.stereo = false
	s.data = data
	return s


## Short attack, then a linear fade to zero at the end (no click).
static func _env(t: float, d: float, attack: float) -> float:
	return minf(t / attack, 1.0) * clampf(1.0 - t / d, 0.0, 1.0)


static func _noise() -> float:
	return randf() * 2.0 - 1.0
