const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.resolve(__dirname, '..');
const toolkit = '/Users/bear/Documents/CoWork/bear-textbooks/books/brutalist-art';
const game = '/Users/bear/Documents/CoWork/bear-textbooks/books/walker/games/walker-jumpman';
const slug = path.basename(root);
const title = 'CSYE 7270: Virtual Environments and Real-Time 3D';
for (const d of ['mp3','media','manim','evidence','remotion/src','remotion/public','_qc','exports/landscape']) fs.mkdirSync(path.join(root,d), {recursive:true});
if (fs.existsSync(path.join(root,'beat_sheet.json'))) throw new Error('Refusing to replace an existing authored/audio-locked sheet.');
const source = '/Users/bear/.codex/attachments/1b7d6005-e804-4136-ab15-f4d38d605f35/pasted-text.txt';
fs.copyFileSync(source,path.join(root,'evidence/course-source.txt'));
fs.copyFileSync(path.join(game,'youtube/claude-liam-walker-jumpman-gamedev/evidence/source-build.json'),path.join(root,'evidence/prior-build.json'));
fs.copyFileSync(path.join(game,'youtube/claude-liam-walker-jumpman-gamedev/evidence/capture-sources.json'),path.join(root,'evidence/prior-captures.json'));
const hash = p => crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const manifest = [{path:'evidence/course-source.txt',source,sha256:hash(source)}];
for (const file of ['godot/features/player/player.gd','godot/features/player/tuning.gd','godot/game/session.gd','godot/levels/first_steps.json','godot/project.godot']) {
 const dest = path.join(root,'evidence/source',file); fs.mkdirSync(path.dirname(dest),{recursive:true}); fs.copyFileSync(path.join(game,file),dest); manifest.push({path:path.relative(root,dest),source:path.join(game,file),sha256:hash(dest)});
}
fs.writeFileSync(path.join(root,'evidence/manifest.json'),JSON.stringify(manifest,null,2));
for (const [name,src] of [['EBGaramond-Regular.ttf','EB_Garamond/static/EBGaramond-Regular.ttf'],['Inter-Regular.ttf','Inter/static/Inter_28pt-Regular.ttf'],['PTMono-Regular.ttf','PT_Mono/PTMono-Regular.ttf']]) fs.copyFileSync(path.join(toolkit,'runtime/fonts',src),path.join(root,'remotion/public',name));
const nm = path.join(root,'remotion/node_modules'); if (!fs.existsSync(nm)) fs.symlinkSync(path.join(toolkit,'runtime/remotion/node_modules'),nm,'dir');
const data = [
 ['B00','REMOTION','A different job',`Please use Walker to explain what I must understand when Claude Code builds my Godot game. That is the question behind C S Y E seventy-two seventy. I'm Liam, in for Professor Bear. This course is about directing and evaluating virtual environments, not collecting impressive-looking code you cannot explain.`,{pattern:'ClaudeComposerAsk',props:{command:'Please use Walker to explain\nwhat I must understand when\nClaude Code builds my Godot game.',topic:'CSYE 7270 · reconstructed course request',segment:'Virtual Environments and Real-Time 3D',greeting:'Hello, Bear',runningText:'',output:[],folderLabel:'walker',modelLabel:'Claude Code',effortLabel:'Course demo',placeholder:'Ask a focused question'}}],
 ['B01','REMOTION','The thesis',`The scarce skill is not typing. It is judgment. Claude can help produce the implementation. You must decide what the game is trying to do, recognize a plausible mistake, and explain why a revision is better. We will follow one small platformer from a vague request to evidence you can defend.`,{pattern:'BrutalistHesitantWriter',props:{text:'The scarce skill is typing.',face:'serif',fontSize:100,lineSpacing:1.25,align:'center',ink:'#3D3929',accent:'#D97757',bg:'#FAF9F5',triggerWords:'typing',replacementWords:'judgment',mistakeRate:0,hesitateWithin:0,hesitateBetween:0,charMs:60,jitter:0,seed:"7270",xOffset:0,yOffset:0,showCaret:true,banner:''}}],
 ['B02','MANIM','Who does what?',`Separate the roles. You supply the intent and acceptance criteria. Walker organizes the brief, build, playtest, inspection, revision, and export cycle. Claude Code proposes and edits code. Godot runs the interactive world. An agent's confident description is not a substitute for observing that world.`,{mode:'roles',labels:['Human','Walker','Claude Code','Godot'],footer:'Intent → workflow → implementation → behavior'}],
 ['B03','VOX','Start from a baseline',`Here is the actual Walker Jumpman starter, before a student's extension. This is an archived frame from the existing project, not a proposed redesign. Establish that baseline first. If you never observe the original controls and level, you will not know whether your changes preserved them.`,{take:'finish',time:0.25,note:'Archived Godot capture · scripted input',label:'Observe before changing'}],
 ['B04','REMOTION','An engine, not a chatbot',`Godot supplies nodes, scenes, rendering, physics, and the running game. G D Script connects those pieces with behavior. The course uses the regular Godot engine. The starter does not require C sharp or the dot net edition. Claude Code is the coding assistant; it is not the engine.`,{mode:'tree',labels:['Godot','Scene','Player','Collision','Camera'],note:'Structure diagram · not an editor recording'}],
 ['B05','MANIM','The production loop',`The Walker loop has six moves: game brief, build, playtest, inspect, revise, export. Notice where inspection sits. Playing reveals an observation; inspection traces its cause; revision changes the cause. Export packages a version. It does not retroactively prove that the version was good.`,{mode:'loop',labels:['Brief','Build','Playtest','Inspect','Revise','Export'],footer:'Export is a deliverable, not a verdict'}],
 ['B06','REMOTION','Check access early',`These exercises assume working Claude Code access through the course's Northeastern arrangements. Check that access early and contact the instructor if it fails. Separate A P I credits are not a starter prerequisite. Install the course-specified Godot version, then open the starter's project file rather than creating an unrelated empty project.`,{mode:'files',labels:['Claude Code access','Godot Engine','godot/project.godot'],note:'Course setup · claude.northeastern.edu'}],
 ['B07','MANIM','Five supervisory capacities',`The course names five supervisory capacities. Plausibility auditing asks whether the result makes sense. Problem formulation defines the task. Tool orchestration orders the work. Interpretive judgment gives the result game-specific meaning. Executive integration keeps the session aimed at one goal. These are the course's vocabulary for supervision, not five buttons in Godot.`,{mode:'capacities',labels:['PA','PF','TO','IJ','EI'],footer:'Audit · formulate · orchestrate · interpret · integrate'}],
 ['B08','REMOTION','PF · Define the task',`Problem formulation begins before prompting. Make the character better is not a specification. Give the character a distinct silhouette while preserving movement speed and collision behavior is closer. Name one concern, an invariant you will preserve, and the files or systems the agent must leave alone.`,{mode:'spec',labels:['Change: character silhouette','Preserve: movement + collision','Do not touch: level geometry'],note:'Example specification · not an executed request'}],
 ['B09','MANIM','TO · Sequence the work',`Tool orchestration is about dependencies. Inspect the existing player first. Change its visual identity next. Check the silhouette in motion. Only then extend the level in a separate change. If art, physics, camera behavior, and geometry all move together, a regression has too many possible causes.`,{mode:'sequence',labels:['Inspect','Character','Test','Level'],footer:'One concern per change'}],
 ['B10','VOX','PA · Hear the wrong note',`Plausibility auditing starts with a specific suspicion. This archived jump frame tells us where the visible character was. It does not prove that every landing works. A new sprite could look centered while its collision shape stays elsewhere. Ask what observation would reveal that mismatch, then test it.`,{take:'jump',time:0.65,note:'Archived Godot capture · scripted input',label:'Appearance is not collision'}],
 ['B11','MANIM','IJ · Judge the experience',`Interpretive judgment supplies the meaning of a result. A collision test can report contact. It cannot decide for your audience whether the landing feels fair or the character reads clearly against the background. Use machine checks as evidence. Make the design judgment yourself, and explain the tradeoff you accepted.`,{mode:'compare',labels:['Contact detected','Landing feels fair'],footer:'Conformance ≠ adequacy'}],
 ['B12','REMOTION','EI · Keep one goal',`Executive integration prevents the session from drifting. The assignment is to change a character and extend a playable level. A proposed inventory system might be clever and completely irrelevant. Keep the brief visible, record deferred ideas, and judge each new task against the goal instead of the agent's enthusiasm.`,{mode:'scope',labels:['Character + level','Inventory','Multiplayer'],note:'Keep the current goal; defer unrelated systems'}],
 ['B13','REMOTION','Read the ownership map',`Now inspect the real starter. Player drawing and movement live in the player script. Level geometry comes from a data file. The session script builds and manages the running world. That ownership map tells you where to ask for a change and where to look when the result surprises you.`,{mode:'files',labels:['player.gd → character','first_steps.json → geometry','session.gd → running world'],note:'Source snapshot · walker-jumpman'}],
 ['B14','VOX','Changing the character',`The first change is a new character identity, not just a new color. Use the baseline as a comparison reference. A student might change the silhouette, face, or accessories while preserving the movement contract. That redesigned character is proposed work here. This film is not presenting an unbuilt student solution as finished gameplay.`,{take:'coyote',time:0.45,note:'Original starter · redesign not yet shown',label:'Change identity; preserve behavior'}],
 ['B15','MANIM','The hidden rectangle',`In this source snapshot, the player's collision rectangle is eighteen by twenty-eight game units. The drawing is a separate concern. Our schematic enlarges both so you can see the difference. Changing the art does not automatically change the collider. If you intentionally change collision, update the specification and the tests too.`,{mode:'collision',labels:['18 × 28','Visual identity','Collision contract'],footer:'Source dimensions · enlarged schematic'}],
 ['B16','REMOTION','Extending the level',`For the first assignment, add at least two new jump-and-landing opportunities and relocate the finish to the new end. More floor is not automatically more play. Show the route, explain the choices it asks of the player, and preserve a reachable start-to-finish experience.`,{mode:'level',labels:['Baseline','Two new landings','New finish'],note:'Proposed extension schematic · not implemented gameplay'}],
 ['B17','VOX','A finish screen is narrow evidence',`This archived completion frame came from scripted input. It demonstrates one successful route in the recorded build. It is not a human playtest, not a measurement of enjoyment, and not evidence about your future extension. Preserve that distinction when you describe tests in your own submission.`,{take:'finish',time:6.5,note:'Archived completion · scripted route only',label:'One route, one recorded build'}],
 ['B18','MANIM','Trace the dangerous middle',`A larger level affects more than one visible platform. The finish position, camera limits, resource references, and runtime behavior may depend on other values. The course calls this the dangerous middle. Follow the dependency links. Do not approve a change merely because the file you edited looks reasonable.`,{mode:'dependencies',labels:['Level width','Camera limits','Finish','Runtime'],footer:'Inspect dependencies, not only the diff'}],
 ['B19','REMOTION','Make the claim falsifiable',`Before the next build, write a prediction that can fail. After extending the level, I can land on both new platforms, reach the new finish, die, and restart at the original spawn. Record the observed result for each part. A claim becomes useful when you know what would contradict it.`,{mode:'tests',labels:['New landings','Finish reachable','Death → restart','Original spawn'],note:'Acceptance plan · results still to be measured'}],
 ['B20','MANIM','A controlled revision',`Suppose the second new landing fails. That is a constructed teaching example, not a new test run. Compare the geometry with the movement you promised to preserve. Adjust one cause, rerun the failing case, then repeat the baseline checks. Quietly weakening the test would hide the problem instead of fixing it.`,{mode:'revise',labels:['Observe','One cause','Rerun','Baseline'],footer:'Constructed example · no invented test result'}],
 ['B21','REMOTION','Week 2 · Prompted art',`In week two, the same supervisory pattern moves to game art. Use tools you can access, compare candidates, record prompts and provenance, and inspect the imported result at game scale. A beautiful isolated image can become an unreadable character. A paid image subscription is not the learning objective.`,{mode:'art',labels:['Prompt','Compare','Import','Readability'],note:'Week 2 · provenance and in-game inspection'}],
 ['B22','MANIM','Week 3 · Blender to Godot',`Week three adds Blender through the community Blender M C P integration. A generated mesh is an intermediate artifact. Inspect its geometry, scale, materials, and exported form, then verify it inside Godot. A correct-looking Blender viewport does not prove that the imported asset behaves correctly in the game.`,{mode:'pipeline',labels:['Prompt','Blender','Export','Godot'],footer:'Inspect geometry · scale · materials'}],
 ['B23','REMOTION','Weeks 4–8 · Behavior and appearance',`The middle of the course connects scenes, collision, and physics to the game design document, then to shaders and materials. Specify what should happen before asking for code. A shader compiling establishes one kind of conformance. Compare controlled inputs and visible output before calling its appearance correct.`,{mode:'roadmap',labels:['4 · Physics','5 · GDD','6–7 · Shaders','8 · Verify'],note:'Fall 2026 teaching sequence'}],
 ['B24','MANIM','Weeks 9–12 · Time matters',`Particles, animation, interaction, and audio unfold over time. A still screenshot cannot show whether an effect starts too early, an animation transition pops, or a sound repeats after restart. Trace the event, the state change, and the visible or audible response. Then test that sequence in the running scene.`,{mode:'timeline',labels:['Event','State','Effect','Restart'],footer:'Weeks 9–12 · verify temporal behavior'}],
 ['B25','REMOTION','Weeks 13–15 · Evidence and integration',`Later work adds profiling, analytics, navigation, behavior trees, procedural content, and appropriately scoped networking, mobile, or extended-reality constraints. These are still Walker and Godot problems. Measure a baseline, justify a focused change, and integrate the result into projects you can reproduce and defend.`,{mode:'roadmap',labels:['13 · Measure','14 · Systems','15 · Defend'],note:'Scope applications to the project'}],
 ['B26','REMOTION','Two clocks, not one',`Modules map one-to-one to companion-book chapters, released one or two per week. Assignments follow a separate clock: one hundred points every ten days. There is an individual project and a group project. Canvas supplies the deadlines and project milestones; this overview does not invent dates or project weightings.`,{mode:'cadence',labels:['Modules → chapters','1–2 per week','100 points / 10 days'],note:'Individual + group projects · deadlines in Canvas'}],
 ['B27','VOX','Play, then explain',`Every assignment also includes a Brutalist Godot explainer. Use a walkthrough to show behavior, a game-development explainer to connect it to implementation, or a game-design-document explainer when that is the assignment's focus. Selected films become class discussion material. Narration should explain actual evidence, not promise footage you never recorded.`,{take:'pause',time:0.5,note:'Archived Godot capture · example evidence',label:'Show behavior; explain the mechanism'}],
 ['B28','MANIM','The learning loop',`Predict, build it, use it, ship it, verify. Predict the result before prompting. Build one focused change. Use it in the game. Ship a reproducible version and explanation. Verify the claims against evidence. This learning loop and Walker's production loop reinforce each other; neither means press generate and trust the result.`,{mode:'learning',labels:['Predict','Build It','Use It','Ship It','Verify'],footer:'A prediction can be wrong; the log should show it'}],
 ['B29','REMOTION','Show the division of labor',`In your sources and Frictional log, name what you contributed and what the A I contributed. Include the wrong turns, the evidence that changed your mind, and what remains unverified. The GitHub version and the Canvas submission must match. A polished film cannot replace an honest account of the work.`,{mode:'ledger',labels:['Human: intent + judgment','AI: proposals + edits','Evidence: tests + revisions'],note:'Frictional · sources · matching version'}],
 ['B30','VOX','Do not confuse recovery with quality',`A failed run can teach more than a confident summary. Here the archive captures the starter's failure state. In your own work, inspect what triggered failure and whether recovery behaves as specified. Then ask the human question: does this teach the player fairly, or merely satisfy a machine check?`,{take:'spike',time:2.0,note:'Archived Godot capture · scripted input',label:'Explain failure and recovery'}],
 ['B31','MANIM','The responsibility boundary',`The agent can help propose acceptance tests, analyze traces, and suggest revisions. Those are useful contributions. It still does not inherit your responsibility for choosing the goal or defending the result. Conformance asks whether the system meets stated checks. Adequacy asks whether those checks and that experience serve the intended player.`,{mode:'boundary',labels:['Conformance','Adequacy'],footer:'Evidence informs the decision; the human owns it'}],
 ['B32','REMOTION','The verdict',`The verdict: this is a course in supervising interactive systems. Learn the subsystems well enough to specify behavior and catch plausible errors. Use Claude Code to accelerate implementation. Use Godot to observe the result. Use the five capacities to explain the decisions that no generated code listing can make for you.`,{pattern:'ClaudeVerdictArtifact',props:{artifactTitle:'Course verdict',artifactHeading:'You remain responsible.',artifactLines:['Specify the behavior.','Inspect the running system.','Distinguish evidence from claims.','Defend the design decision.']}}],
 ['B33','REMOTION','Your turn',`Your turn. Please use Walker to inspect Jumpman, preserve its movement, and propose a new character and two new landings. Start with that prompt, then review the proposed changes before accepting them. Your evidence should show the baseline, the extension, a failure and restart, and one revision you can explain.`,{pattern:'ClaudeComposerAsk',props:{command:'Please use Walker to inspect Jumpman,\npreserve its movement, and propose a\nnew character and two new landings.',topic:'Your Turn · suggested prompt',segment:'Predict before you prompt',greeting:'Your turn, Bear',runningText:'',output:[],folderLabel:'walker-jumpman',modelLabel:'Claude Code',effortLabel:'Course demo',placeholder:'Begin with a testable brief'}}],
 ['B34','REMOTION','Outro','',{pattern:'ClaudeTitleOutro',props:{title,slug}}],
];
const beats = data.map(([beat_id,lane,heading,narration_text,p],i)=> {
 const special = p.pattern;
 const remotion = special ? p : lane==='REMOTION' ? {pattern:'CourseScene',props:{heading,...p}} : lane==='VOX' ? {pattern:'CourseEvidence',props:{heading,...p,image:`${beat_id}.png`}} : undefined;
 return {beat_id,act:i<2?'Opening':i<7?'1 · Roles':i<13?'2 · Capacities':i<21?'3 · Worked example':i<27?'4 · Semester':i<32?'5 · Evidence':'Closing',heading,narration_text,engine:'kokoro',voice:'am_onyx',estimated_duration_s:Math.max(10,narration_text.split(/\s+/).length/2.6),tail_silence_s:0,lead_silence_s:beat_id==='B01'?0.8:0,shot:{type:lane==='MANIM'?'MANIM':lane==='VOX'?'STILL':'REMOTION',lane,scene_type:lane==='MANIM'?'mechanism':lane==='VOX'?'archival-evidence':special?'bookend':'explanatory-interface',motion:lane==='MANIM'?'draw-and-transform':lane==='VOX'?'evidence-reveal':'staged-reveal',show:[`Reveal ${heading}.`,lane==='VOX'?'Hold the real archived frame, expose its provenance, and distinguish its narrow claim.':'Build the relation in order; highlight the active element as narration explains it.','Hold the resulting relation without adding unrelated decorative motion.'],...(remotion?{remotion}:{}),...(lane==='MANIM'?{manim:{scene:beat_id,...p}}:{}),...(lane==='VOX'?{evidence:p,fill_plan:{responsible:'human',need:'Existing project evidence, not a new stock image'}}:{})},sources:[i<2||i>=21?'evidence/course-source.txt':'evidence/course-source.txt; evidence/source; evidence/prior-build.json'],epistemic_status:p.note?.includes('Proposed')||p.footer?.includes('Constructed')?'constructed teaching example':'course source / identified archival evidence'};
});
const sheet={metadata:{slug,title,persona:'Liam',voice_kokoro:'am_onyx',voice:'am_onyx',engine:'kokoro',palette:'claude',aspect_ratio:'16:9',width:3840,height:2160,fps:24,format:'ai-deep-explainer',source:'evidence/course-source.txt',publication:'not authorized for this new film',build_status:'authored, narration not yet measured',captions:'SRT sidecar only; no burned subtitles'},beats};
fs.writeFileSync(path.join(root,'beat_sheet.json'),JSON.stringify(sheet,null,2));
fs.writeFileSync(path.join(root,'SCRIPT.md'),`# ${title}\n\nPersona: Liam. Sources: supplied course text plus identified existing game evidence.\n\n`+beats.map(b=>`## ${b.beat_id} — ${b.heading}\n\n${b.narration_text||'[Regular outro jingle; no narration.]'}\n`).join('\n'));
fs.writeFileSync(path.join(root,'SHOTLIST.md'),'# Shot list\n\n'+beats.map(b=>`- ${b.beat_id} · ${b.shot.lane} · ${b.heading} · ${b.shot.show.join(' ')}`).join('\n')+'\n');
fs.writeFileSync(path.join(root,'CHECKS-REPORT.md'),'# Previz design checks\n\n35 beats: 30 body, 5 bookends. Body: 12 Manim (40%), 12 Remotion (40%), 6 VOX archival stills (20%).\n\nSHOW 34, HOLD 1 (locked outro), generic prose CARD 0, PUNT 0. Evidence holds contain named real project images, not stock padding. Five acts: roles, capacities, worked extension, semester sequence, evidence. Framework precedes examples; worked example explicitly separates source dimensions from proposed extension; counterexample is labelled constructed; Your Turn supplies a bounded prompt and evaluation criteria.\n\nRuntime, audio, typography and image QC are pending. No human approval or completed render is claimed.\n');
fs.writeFileSync(path.join(root,'SOURCES.md'),`# Sources and attribution\n\n- User-provided course description, copied without changing wording to evidence/course-source.txt. This controls the Fall 2026 course claims, capacities and sequence.\n- Existing walker-jumpman code and build receipts: evidence/source, evidence/prior-build.json, evidence/prior-captures.json; hashes in evidence/manifest.json. Archived captures used scripted input, not human playtests. No fresh game test was run for this film.\n- [Godot nodes and scenes](https://docs.godotengine.org/en/stable/getting_started/step_by_step/nodes_and_scenes.html), consulted September 10, 2026, supports the short engine/scene explanation.\n- [Northeastern Claude access](https://claude.northeastern.edu/): link supplied by the course; live page fetch returned 502, so no current sign-in steps or licensing promises are inferred.\n- [Walker Jumpman starter](https://github.com/nikbearbrown/walker-jumpman).\n- Assignment-one requirements and Frictional/version alignment: ../../assignments/01-extend-walker-jumpman.md in this course.\n- Brutalist sandbox toolkit ${toolkit}: existing Claude composer, hesitant writer, verdict and locked outro components. Hesitant writer source carries an unresolved upstream author note; no new publication rights claim is made.\n- Voice: locally generated Kokoro am_onyx as the Liam persona; not a recording of Professor Bear. No paid image, voice, or stock service was used.\n- Fonts: toolkit EB Garamond, Inter and PT Mono; bundled open font license files retained with toolkit.\n\nAI contribution: script adaptation, diagrams, build code and automated QC. Human contribution: supplied course policy, project goal and original materials. Human review of this film remains pending.\n`);
fs.writeFileSync(path.join(root,'FACTCHECK.md'),'# Claim audit\n\nPASS — source audit, not a fresh game execution. Course statements follow the supplied description. Source snapshot supports file ownership and the 18 × 28 collision rectangle. Recorded success demonstrates only a scripted route. The extension, faulty second landing, and acceptance plan are explicitly constructed/proposed; there is no invented student work, fresh test result, frame-rate measurement, or human playtest. Course-specific access is attributed to the course, not to an unavailable live NEU page. Modules and assignments have separate cadences. No exact assignment count, project weights or due dates are invented.\n\nVisual inspection and final media checks remain pending.\n');
fs.writeFileSync(path.join(root,'BUILD-PROMPT.md'),'# Build request\n\nAI deep explainer, Liam persona, CSYE 7270 Virtual Environments and Real-Time 3D, based on the attached course text. Use the sandbox deep-explainer, AI-explainer, explainer, duration-planner, your-turn and typography workflows. VOICE-LOCK overrides obsolete human pre-render gates. Produce local 4K landscape review media with regular outro. Do not publish. Preserve source course and game.\n');
fs.writeFileSync(path.join(root,'PROMPTS.md'),'# Prompt provenance\n\nCold open and Your Turn show authored suggested prompts, not historical Claude sessions. Exact prompts live in beat_sheet.json. All diagrams are code-native. No image generation prompt or fabricated engine screenshot was used.\n');
fs.writeFileSync(path.join(root,'BUILD-LOG.md'),'# Build log\n\n- Read source and mapped course claims to five acts.\n- Consulted scene library; reused four canonical bookends. No suitable existing course-specific mechanism scene found.\n- Pantry search for walker jumpman godot found no relevant stock; unrelated Walker-name results rejected. Real project evidence selected instead.\n- Authoring complete; audio and render pending.\n');
console.log(JSON.stringify({root,beats:beats.length,words:beats.reduce((n,b)=>n+b.narration_text.split(/\s+/).filter(Boolean).length,0),body:{MANIM:12,REMOTION:12,VOX:6}}));
