"""Write SHOTLIST.md from beat_sheet.json and evidence/media-provenance.json (no hand-copied intervals)."""
from common import REEL, FPS, load_json, render_frames

LABELS = {
    'B01': 'ClaudeComposerAsk · Reconstructed prompt (not a saved chat)',
    'B02': 'BrutalistHesitantWriter · one working correction: generated → designed',
    'B03': 'Card · requirements from the author’s film brief; build 74c0443, capture copy 5266946',
    'B04': 'GodotDesignBoard (CONCEPT.md line 7 exact; pillar cards interpreted) → Scripted-input capture',
    'B05': 'Card · CHARACTER-SHEET.md lines 9, 10, 46 exact, palette swatches, collision.png · not gameplay',
    'B06': 'Three cards · verbatim prompts · Prompt drafted by Claude, sent by the author in the Gemini app',
    'B07': 'Card · RAW GEMINI OUTPUT — not in engine',
    'B08': 'Source view (Python cleanup tool, not a Godot view) · tools/clean_sprites.py 442–459',
    'B09': 'Card · Asset file preview — not gameplay (20× nearest)',
    'B10': 'GodotDevWorkbench · Godot editor reconstruction · player.gd 17–26',
    'B11': 'Scripted-input capture',
    'B12': 'Source view (Python cleanup tool) · tools/clean_sprites.py 130–151',
    'B13': 'Card · Contact sheets — not gameplay → Scripted-input capture',
    'B14': 'GodotDevWorkbench · Godot editor reconstruction · player.gd 101–112',
    'B15': 'Scripted-input capture + event labels (growl · 0.5 s, lunge, hit, cast, wolf down, gone)',
    'B16': 'GodotDevWorkbench · Godot editor reconstruction · audio_director.gd 40–50',
    'B17': 'Scripted-input capture + sound-ID labels; footage silent under narration',
    'B18': 'SLICE AUDIO — no narration · scripted-input capture',
    'B19': 'GodotDevWorkbench · Godot editor reconstruction · main.gd 64–69',
    'B20': 'Scripted-input capture (narrated, Held frame) → SLICE AUDIO — no narration',
    'B21': 'GodotDevWorkbench · Godot editor reconstruction · test_sound_triggers.gd 118–123',
    'B22': 'Card · Recorded command output (re-run on a fresh copy of 74c0443)',
    'B23': 'Card · models, contributions, credits (Powered by Stability AI + license notice)',
    'B24': 'ClaudeVerdictArtifact',
    'B25': 'ClaudeComposerAsk · suggested prompt, not a saved chat',
    'B26': 'ClaudeTitleOutro (locked) · silent',
}


def take_desc(p):
    if 'footage' in p:
        return take_desc(p['footage'])
    if 'take' in p:
        s = f"{p['take']} {p['take_start_s']:.3f}–{p['take_end_s']:.3f} s (src frames {p['src_frame_start']}–{p['src_frame_end'] - 1}, every 2nd)"
        if p.get('held_frames'):
            s += f" + {p['held_frames']} held frames"
        return s
    if 'video' in p:
        return take_desc(p['video']) + f" · audio samples {p['audio']['start_sample']}–{p['audio']['end_sample']}"
    return ''


def main():
    sheet = load_json(REEL / 'beat_sheet.json')
    prov = load_json(REEL / 'evidence' / 'media-provenance.json')['beats']
    rows, t = [], 0.0
    for b in sheet['beats']:
        bid = b['beat_id']
        n = render_frames(b['actual_duration_s'])
        p = prov.get(bid)
        parts = []
        if isinstance(p, list):
            parts = [take_desc(x) for x in p if take_desc(x)]
        elif isinstance(p, dict):
            if 'narrated' in p:
                parts = [take_desc(p['narrated']), 'slot: ' + take_desc(p['slot'])]
            elif take_desc(p):
                parts = [take_desc(p)]
        rows.append(f"| {bid} | {t:6.2f} | {n / FPS:5.2f} | {b['heading']} | {LABELS[bid]} | {'; '.join(parts) or '—'} |")
        t += n / FPS
    text = f"""# SHOTLIST — {sheet['metadata']['title']}

> Generated by `scripts/shotlist.py` from `beat_sheet.json` and `evidence/media-provenance.json`. Native 3840x2160, 30 fps. Total {t:.2f} s.

**Gameplay rule.** Every gameplay interval is a Movie Maker take (`capture/run-0N.avi`, 60 fps, scripted input, gate PASS) at normal speed: every second source frame for 30 fps, cut to exactly the beat's frame count, so the compiler never retimes, slows or center-cuts it. The only hold is B20's, labelled **Held frame** on screen. Footage is silent under narration; B18 and the B20 slot carry the same take's own audio cut sample-exactly to the same interval (48 kHz: 800 samples per source frame).

**Derived times.** The B15 "growl · 0.5 s" label starts 10 ticks before the driver released "right" (it releases 10 ticks after first reading the wolf in GROWL; ±1 tick) and lasts GROWL_TIME 0.5 s (wolf.gd line 21); "gone" is 0.6 s after the logged wolf_down (DOWN_TIME, line 27). Every other label time is a logged game event.

| Beat | Start s | Dur s | Heading | On screen / label | Take interval |
|---|---|---|---|---|---|
""" + '\n'.join(rows) + '\n'
    (REEL / 'SHOTLIST.md').write_text(text, encoding='utf-8')
    print(f'SHOTLIST.md: {len(rows)} beats, {t:.2f} s')


if __name__ == '__main__':
    main()
