#!/usr/bin/env python3
"""Write SHOTLIST.md, COMPONENTS.md, PROMPTS.md and RIFF.md from the beat sheet
and gamedev-evidence.json, so the paperwork cannot drift from the film.

    python3 tools/make_docs.py
"""
import json
from pathlib import Path

REEL = Path(__file__).resolve().parents[1]
sheet = json.loads((REEL / "beat_sheet.json").read_text())
ev = json.loads((REEL / "gamedev-evidence.json").read_text())
beats = sheet["beats"]
title = sheet["metadata"]["title"]

NEXT = {  # one suggested experiment per evidence beat (RIFF.md)
    "B03": "Play the same 17 s with the game muted (N, M) and list which events are still readable from the picture alone.",
    "B07": "Press Enter during the title fade-in of a replay and confirm the title shows only once per run.",
    "B09": "Set turn_hold_time to 0.0 and play a reverse run: does the tap-to-turn disappear, as the code predicts?",
    "B11": "Mash jump for 3 s on the ground and compare the Sfx count with the takeoffs in the debug line.",
    "B13": "Jump straight up, then while moving, and read which falling pose the debug line shows each time.",
    "B17": "Walk into the spikes again inside 1.2 s: the log should show no second heart lost.",
    "B19": "Try width 4 and 12 in outline.tres and judge the hair against the wheat at game size, not zoomed.",
    "B21": "Change STOMP_MARGIN and re-run the stomp from the top of a full jump (the Your Turn prompt).",
    "B23": "Press slash with the goblin 140 px away: the hitbox should be live but miss.",
    "B25": "Take the pickup, then a spike hit: gear lost, hearts unchanged — confirm in the log.",
    "B27": "Fall before reaching the waystone: he should get back up at the start, not at x 4120.",
    "B29": "Lose the last heart to a fall instead of a hit: same start-over, no CHAR-DEFEAT.",
    "B31": "Get hit, then pause within 0.6 s: the music should sit at −12 dB, not −18.",
    "B33": "Mute both buses and play to the circle: same ticks, as the checks assert.",
    "B35": "Press Enter on the end card's first frame: the code says it works at once.",
    "B37": "Make one check fail on purpose (move a sound file away) and confirm the exit code is 1.",
}


def dur(b):
    return b.get("render_duration_s") or b.get("actual_duration_s") or 0.0


def visual(b):
    s = b["shot"]
    if s.get("capture_plan"):
        cp = s["capture_plan"]
        segs = ", ".join(f"{x['from']}–{x['to'] - 1}" + ("" if x["speed"] == 1 else f" @{x['speed']}×") for x in cp["segments"])
        hold = cp.get("held_final_frames", 0)
        return f"`{cp['capture']}` frames {segs}" + (f" + held {hold} f" if hold else "")
    if s.get("still_plan"):
        return f"still `{s['still_plan']['image']}`"
    r = s["remotion"]
    p = r["props"]
    extra = f" `{b['excerpt']['path']}:{b['excerpt']['start_line']}–{b['excerpt']['end_line']}`" if b.get("excerpt") else ""
    return f"{r['pattern']}" + (f" ({p.get('mode')})" if p.get("mode") else "") + extra


t = 0.0
rows = []
for b in beats:
    rows.append(f"| {b['beat_id']} | {t:6.1f} | {dur(b):5.1f} | {b['act']} | {visual(b)} |")
    t += dur(b)
(REEL / "SHOTLIST.md").write_text(
    f"# SHOTLIST — {title}\n\n{len(beats)} beats, {t:.1f} s ({int(t // 60)}:{t % 60:04.1f}), 3840×2160, 30 fps. "
    "Generated by `tools/make_docs.py` from `beat_sheet.json`.\n\n"
    "Every code beat is followed by its visible result (`code-then-result-v1`). Gameplay frames are the hashed captures "
    "(CAPTURE.md); REPLAY and held frames are labelled on screen.\n\n"
    "| Beat | Start s | Dur s | Act | Visual |\n| --- | ---: | ---: | --- | --- |\n" + "\n".join(rows) + "\n")

comp = ["| Component | Files | Beats | What it does |", "| --- | ---: | --- | --- |"]
for c in ev["components"]:
    comp.append(f"| `{c['id']}` | {len(c['files'])} | {', '.join(c['beat_ids'])} | {c['explanation']} |")
pairs = ["| Code beat | Source | Result beat | Observed |", "| --- | --- | --- | --- |"]
ex = {e["beat_id"]: e for e in ev["excerpts"]}
for p in ev["code_result_pairs"]:
    e = ex[p["code_beat"]]
    pairs.append(f"| {p['code_beat']} | `{e['path']}:{e['start_line']}–{e['end_line']}` | {p['result_beat']} | {p['observation']} |")
excl = "\n".join(f"- `{x['path']}`: {x['reason']}" for x in ev["exclusions"])
(REEL / "COMPONENTS.md").write_text(
    f"# COMPONENTS — {title}\n\nThe game folder `game/` at `{ev['game']['revision'][:7]}`: {len(ev['files'])} authored files "
    f"(`.uid` identifiers and `.godot/` excluded by the contract), every one assigned to a component in `gamedev-evidence.json`.\n\n"
    + "\n".join(comp) + "\n\n## Code → result pairs\n\n" + "\n".join(pairs)
    + f"\n\n## Exclusions\n\n{excl}\n\n## Not shown as code, and why\n\n"
    "- `level_1.tscn`, `main.tscn`, `project.godot`: shown as reconstructed scene trees with their real positions and names (B04, B05), not as excerpts.\n"
    "- `backdrop.gd`, `ground_segment.gd`, `hearts.gd`, `hud.gd`, `spikes.gd`, `waystone.gd`, `portal.gd`, `sword_pickup.gd`, `flying_gear.gd`, `rudy_look.gd`, `sfx.gd`: their behaviour is shown in play and named in narration or source notes; the film excerpts the lines that decide state.\n"
    "- `tests/capture.gd`: the project's own screenshot/mix tool; it teleports Rudy, so none of its output is used as gameplay footage.\n"
    "- Texture, audio and `.import` files: inventoried and hashed; the film shows the generated art in play and one asset's full trace (CHAR-HURT).\n")

pr = [f"# PROMPTS — {title}\n", "Every prompt shown or read in the film.\n"]
for b in beats:
    r = b["shot"].get("remotion", {})
    if r.get("pattern") == "ClaudeComposerAsk":
        p = r["props"]
        pr.append(f"## {b['beat_id']} — {p['greeting']}\n\n**Status:** {'reconstructed prompt — illustrative, not a transcript' if b['beat_id'] == 'B00' else 'suggested prompt for the viewer'}\n\n```text\n{p['command']}\n```\n")
        if p.get("output"):
            pr.append("On-screen result lines (each checked in FACTCHECK.md):\n\n" + "\n".join(f"- {o}" for o in p["output"]) + "\n")
pr.append("## B15 — generation prompts quoted from the project\n\n"
          "- Pose template (design/generation-prompts.md), `[POSE]` = CHAR-HURT: “hurt: recoiling from a hit coming from the right, "
          "leaning back, eyes squeezed shut, arms flung out”.\n- Edit, Gemini chat turn 10 (ASSET-LOG.md): “人物应该向后仰而不是现在的向前扑。” "
          "[He should lean back, not lunge forward as he does now.]\n\nThese are shuai-z's prompts from the project's logs, shown as such.\n")
(REEL / "PROMPTS.md").write_text("\n".join(pr))

rf = [f"# RIFF — {title}\n",
      "Liam, in for Bear (Kokoro `am_onyx`). Observations come from the captures and their logs; mechanisms from the source "
      "named in the preceding code beat. Scripted input is never called a playtest; feel and fun are not judged here.\n",
      "| Beat | Artifact + range | Visible observation | Interpretation (source) | Narration | Next experiment |",
      "| --- | --- | --- | --- | --- | --- |"]
for i, b in enumerate(beats):
    s = b["shot"]
    if not (s.get("capture_plan") or s.get("still_plan")):
        continue
    prev = beats[i - 1]
    src = f"`{prev['excerpt']['path']}:{prev['excerpt']['start_line']}–{prev['excerpt']['end_line']}`" if prev.get("excerpt") else "B02 (concept)"
    narr = b["narration_text"] or "— (no narration: the slice's own audio only)"
    rf.append(f"| {b['beat_id']} | {visual(b)} | {s['observation']} | {src} | {narr} | {NEXT.get(b['beat_id'], '')} |")
(REEL / "RIFF.md").write_text("\n".join(rf) + "\n")
print(f"docs written; film {t:.1f} s")
