"""Generate this new film's recipe; never rewrite an existing authored sheet."""
import hashlib,json,shutil,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ART=Path('/Users/bear/Documents/CoWork/bear-textbooks/books/brutalist.art')
GAME=Path('/Users/bear/Documents/CoWork/bear-textbooks/books/walker/games/walker-jumpman')
WALK=GAME/'youtube/claude-liam-walker-jumpman-walkthrough'
DEV=GAME/'youtube/claude-liam-walker-jumpman-gamedev'
TITLE='Assignment 1: Extend Walker Jumpman'
SLUG=ROOT.name
if (ROOT/'beat_sheet.json').exists(): raise SystemExit('Existing recipe preserved.')
for p in ['evidence','media','mp3','audio','_qc','exports/landscape','remotion/src','remotion/public','_project']:(ROOT/p).mkdir(parents=True,exist_ok=True)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):(ROOT/p).write_text(json.dumps(x,indent=2)+'\n')
manifest=json.loads((GAME/'evidence/build-manifest.json').read_text())
for p,h in manifest['source_sha256'].items():
    if sha(GAME/p)!=h: raise RuntimeError('Source changed: '+p)
save('evidence/source-build.json',manifest)
subprocess.run(['rsync','-a','--exclude=.godot',str(GAME/'godot')+'/',str(ROOT/'_project')+'/'],check=True)
shutil.copy2(ROOT.parents[1]/'canvas/02-assignment-1-extend-walker-jumpman.html',ROOT/'evidence/assignment.html')
captures=[]
for take in ['finish','spike','jump','pause','controls','coyote','buffer']:
    source=WALK/'capture'/f'{take}.mp4'; receipt=json.loads((WALK/'capture'/f'{take}-receipt.json').read_text())
    assert receipt['build_id']==manifest['build_id'] and receipt['video_sha256']==sha(source)
    shutil.copy2(source,ROOT/'media'/f'source-{take}.mp4')
    for suffix in ['-receipt.json','-inputs.jsonl','-states.jsonl']:
        shutil.copy2(WALK/'capture'/f'{take}{suffix}',ROOT/'evidence'/f'{take}{suffix}')
    captures.append({'take':take,'source':str(source),'path':f'media/source-{take}.mp4','sha256':sha(source),'build_id':manifest['build_id'],'method':'archived actual Godot output; scripted normal Input events; not a human playtest'})
save('evidence/capture-sources.json',captures)
for name,src in [('EBGaramond-Regular.ttf','EB_Garamond/static/EBGaramond-Regular.ttf'),('Inter-Regular.ttf','Inter/static/Inter_28pt-Regular.ttf'),('PTMono-Regular.ttf','PT_Mono/PTMono-Regular.ttf')]:
    shutil.copy2(ART/'runtime/fonts'/src,ROOT/'remotion/public'/name)
if not (ROOT/'remotion/node_modules').exists():(ROOT/'remotion/node_modules').symlink_to(ART/'runtime/remotion/node_modules',target_is_directory=True)
beats=[];excerpts=[];pairs=[]
def add(title,text,pattern=None,props=None,take=None,still=None):
    bid=f'B{len(beats):02d}'
    shot={'type':'FOOTAGE' if take else 'REMOTION','source':'own','classification':'SHOW','visual_intent':title,'show':[{'at':'beat','event':title}]}
    if pattern:shot['remotion']={'pattern':pattern,'props':props or {}}
    if take:shot['evidence_media']=f'media/source-{take}.mp4'
    if still:shot['evidence_media']=f'media/{still}'
    b={'beat_id':bid,'heading':title,'narration_text':text,'engine':'kokoro','voice':'am_onyx','shot':shot}
    if take:b['gameplay_take']=take
    if still:b['still']=still
    beats.append(b);return bid
def board(title,text,rows,note,mode='rows'):
    return add(title,text,'AssignmentBoard',{'title':title,'rows':rows,'note':note,'mode':mode})
def code(title,text,file,start,end,notes,cues):
    actual='\n'.join((GAME/'godot'/file).read_text().splitlines()[start-1:end])
    bid=add(title,text,'GodotDevWorkbench',{'mode':'code','title':title,'project':'walker-jumpman','path':file,'source':'Exact starter source · next: the visible result','code':actual,'startLine':start,'codeFontSize':30,'notes':[{'label':k,'value':v} for k,v in notes],'output':['Starter code, not a completed student extension.'],'cues':[]})
    beats[-1]['cue_phrases']=[{'phrase':p,'line':l,'label':n} for p,l,n in cues]
    excerpts.append({'beat_id':bid,'path':file,'start_line':start,'end_line':end,'text':actual});return bid
def result(previous,title,text,observation,take=None,still=None):
    bid=add(title,text,None if take else 'EnginePreview',None if take else {'title':title,'image':still,'note':'Actual Godot vector draw · staged art inspection, not playtest','collider':still=='player-collider.png'},take,still)
    pairs.append({'code_beat':previous,'result_beat':bid,'observation':observation,'media':{'path':beats[-1]['shot']['evidence_media']}})
ask='Please use Walker to inspect Jumpman,\nthen help me change its character\nand extend its first level.'
composer=lambda prompt,segment:{'command':prompt,'topic':'CSYE 7270 · suggested prompt, not a saved chat','segment':segment,'greeting':'Hello, Bear','runningText':'','output':[],'folderLabel':'walker-jumpman','modelLabel':'Claude Code','effortLabel':'','placeholder':''}
add('One assignment, one traceable game',"Please use Walker to inspect Jumpman, then help me change its character and extend its first level. I'm Liam, in for Professor Bear. This is Assignment One for C S Y E seventy-two seventy. We will connect setup, source code, and the running game, then show what you must change and verify.",'ClaudeComposerAsk',composer(ask,TITLE))
add('Do not merely copy it',"The assignment is not to copy a working game. It is to extend one and explain the consequences. Each code excerpt here is followed by its visible result. The footage shows the unchanged starter, driven by scripted input. Your character, extension, and human playtest are still your work to do.",'BrutalistHesitantWriter',{'text':'Your job is to copy it.','triggerWords':'copy','replacementWords':'extend','fontSize':100,'mistakeRate':0,'hesitateWithin':0,'hesitateBetween':0,'charMs':60,'jitter':0,'seed':SLUG,'face':'serif','align':'center'})
beats[-1]['lead_silence_s']=.8
add('1 · Download the regular Godot engine',"Start with the regular Godot Engine, not the dot net edition. This Mac demonstration uses the official macOS download page. The starter was verified with version four point seven point two and G D Script. On another operating system, choose its matching download. These exercises also assume your course Claude Code access; separate A P I credits are not required.",'WalkerGodotSetup',{'mode':'download','title':'Download the regular Godot engine','version':'4.7.2','source':'godotengine.org/download/macos/ · reconstructed page · Mac demo','sparkLine':'GDScript starter · no C# or .NET required'})
board('2 · Download both repositories',"Clone Walker and Walker Jumpman into a working folder, or use Code, Download ZIP on each GitHub page and unzip them. Keep both repository addresses exact. One important limitation: the public Walker README still describes its older Unity workflow. Do not mistake that for a Godot installer. Jumpman is a standalone Godot project and can run without a Walker executable.",[
 ['Walker · reference project','git clone https://github.com/nikbearbrown/walker.git'],
 ['Jumpman · runnable starter','git clone https://github.com/nikbearbrown/walker-jumpman.git'],
 ['No terminal alternative','GitHub → Code → Download ZIP → unzip']],
 'Suggested commands · not a recorded terminal session','repos')
board('3 · Import the existing game',"In Godot's Project Manager, choose Import and locate godot slash project dot godot inside the Jumpman download. Import and edit, then press F six only for a selected scene, or F five to run the project. Use F five here. The starter already selects its main scene. Creating a new empty project would not import this game.",[
 ['Project Manager','Import, not Create'],['Choose the existing file','walker-jumpman/godot/project.godot'],['Run the project','F5 → Enter to start']],
 'Instruction sequence · not an editor recording')
add('Observe the baseline first',"Watch the starter at normal simulation speed: the first step, spikes, two gaps, another step, and the finish. The completion screen leads to a clean replay. This is one recorded scripted route, not proof that every route works. Before editing, play the original yourself and keep that baseline in your test report.",take='finish')
board('Your two required changes',"Assignment One has two concrete changes: a recognizable new main character, not just a rename or recolor, and a level extension beyond the starter with at least two new landings that require jumps. Move the finish to the new end. A longer empty floor is not the extension. Preserve the existing movement and recovery behavior while you change one concern at a time.",[
 ['Character','New silhouette or recognizable features'],['Level','Two new jump landings + relocated finish'],['Preserve','Movement, collision, failure, retry, pause']],
 'Required student changes · the starter footage is not a submitted solution')
b=code('Character art is drawing code',"Here is the character's drawing code. The first rectangle gives the body its dark outline. The blue rectangle sits inside it. The orange strip is the scarf, followed by feet and an eye that changes side with facing. There is no sprite sheet to replace. For your first revision, change this visual identity while leaving movement alone.",'features/player/player.gd',74,80,[('Art','Original procedural rectangles'),('Your change','A distinct shape or features')],[('first rectangle',74,'Dark body outline'),('orange strip',76,'The scarf'),('eye',79,'Facing changes the eye')])
result(b,'The rectangles become a character',"Now those rectangles are visible, enlarged from the actual Godot drawing routine. The scarf crosses the body and the eye shifts with facing. This is a staged art preview, not gameplay. Judge the silhouette here, then check the new character at game size, against the background, while moving and jumping.",'Actual unmodified player drawing at two facing values.',still='player-art.png')
b=code('The collision box is a different object',"The collision shape is eighteen by twenty-eight game units, centered fourteen units above the player's origin. That places the origin at the feet. These lines, not the scarf drawing, define the rectangle used for physics. Preserve this contract initially so an art change does not secretly become a movement change.",'features/player/player.gd',23,28,[('Physics size','18 × 28 game units'),('Center offset','(0, −14) from the feet')],[('eighteen by twenty-eight',24,'Shape size'),('fourteen units',27,'Center above feet')])
result(b,'The scarf is not the collision boundary',"The diagnostic outline comes from the actual CollisionShape node in this staged preview. Notice how the scarf protrudes beyond the physics rectangle. Appearance and collision already differ slightly in the starter. If your redesign makes that difference misleading, inspect it in motion and explain any intentional collider change instead of assuming the art changed physics.",'Actual collider node dimensions rendered over player art; overlay labelled diagnostic.',still='player-collider.png')
b=code('Movement uses rates, not teleports',"Horizontal velocity moves toward a target using acceleration while a key is pressed and deceleration when it is released. Facing changes with the direction. Gravity updates vertical velocity separately. Tuning lives in the player resource; the remaining jump logic limits when another jump is allowed. Do not raise those limits to disguise an impossible new landing.",'features/player/player.gd',56,60,[('Separate concerns','Direction, speed, gravity'),('Preserve first','Existing tuning and jump contract')],[('Horizontal velocity',57,'Approach the target speed'),('Facing changes',59,'Remember the direction'),('Gravity',60,'Update vertical velocity')])
result(b,'Watch acceleration and braking',"The player moves left to the boundary, accelerates to the right, then stops when the input is released. Opposing keys cancel. Watch the eye follow the chosen direction. This normal-input recording is the visible result of the movement code. Preserve those controls while replacing the art, and separately test jump, landing, and the one-jump contract.",'Normal-input capture shows movement, braking, opposing-key cancellation and facing.',take='controls')
b=code('Level geometry starts as data',"The level file lists rectangles as x, y, width, and height. Solids become both drawn platforms and physical bodies when the session builds the world. The finish is a separate trigger. Extend this layout with two meaningful new jump landings, update the level width, and move the finish. Do not confuse adding a rectangle with proving that it is reachable.",'levels/first_steps.json',5,10,[('Rectangle contract','x, y, width, height'),('Your extension','Geometry + width + finish')],[('lists rectangles',8,'The solids array'),('finish',10,'Finish trigger')])
result(b,'Data becomes steps, gaps, and a finish',"Follow the feet across the platforms. The player lands on real solids, clears the gaps, and eventually touches the finish trigger. Those are the observable consequences of the layout. Your new section should ask for actual jumps and remain reachable with the original movement. A successful starter route does not validate coordinates you have not tested yet.",'Same-build route demonstrates solids, gaps and the finish trigger.',take='finish')
b=code('A useful bug seam: hazard art',"The hazard drawing reads each hazard's horizontal position, but its vertical coordinates are hard-coded to three hundred twenty and three hundred four. That is a seam students can miss. Move hazard data vertically without updating its drawing and the picture may no longer match the collision. Trace both sides of the change.",'game/session.gd',198,201,[('Data-driven','Horizontal position'),('Hard-coded','Vertical drawing coordinates')],[('horizontal position',200,'Read x from data'),('hard-coded',201,'Drawing y values remain fixed')])
result(b,'Visible spikes, failure, and retry',"Walk into the visible spikes. The game names the failure, increments the retry count, and returns the player to the start. The starter drawing and collision agree in this run. If you move or redraw hazards, repeat this test. A dangerous object should fail where it looks dangerous, and the retry should still be cheap.",'Normal-input spike contact produces failure, one retry and restart.',take='spike')
b=code('The camera depends on the level width',"This camera line looks one hundred units ahead of the player and clamps the camera center between the start and the level width minus three hundred twenty. That half-width comes from the logical six-forty-wide view. A wider level changes the camera boundary. It does not automatically extend hard-coded background drawing or reposition every label.",'game/session.gd',153,155,[('Follow','Player x + 100'),('Clamp','320 … level width − 320')],[('one hundred',153,'Look ahead, then clamp')])
result(b,'The world moves; the interface stays',"Watch the world scroll as the player approaches the end. The title and control hints stay fixed because the interface is separate from the world camera. After extending the map, inspect both new landings, the right edge, the finish label, and the background. Test what the player can see before a jump, not only whether the jump is physically possible.",'Camera scroll and fixed HUD visible during the same-build route.',take='finish')
b=code('The progress bar hides another dependency',"The progress bar subtracts the original spawn x, sixty-four, then divides by eight hundred fifty-two. That is the original distance from spawn to the finish trigger. Moving the finish without revisiting this expression can make the bar fill too early. A game can be playable and still tell the player the wrong thing.",'ui/hud.gd',23,25,[('Old span','916 − 64 = 852'),('After extension','Revisit the progress calculation')],[('subtracts',24,'Original spawn and finish span'),('bar',25,'Draw the resulting proportion')])
result(b,'Watch the bar approach the old finish',"Look at the thin green bar below the controls. It grows along this recorded route and reaches its end near the old finish. After your extension, compare that visual promise with the actual new goal. Verify the interface and level together; checking only the platform coordinates would miss this dependency.",'HUD progress changes along the baseline route; no extension result is claimed.',take='finish')
b=code('Pause switches the player off',"Pause changes the session state and disables the player. Resume restores playing, then clears the pending jump request and requires a release. This is a local pause contract, not a blanket pause of the entire scene tree. Preserve it while adding your new section, and test the controls after a restart as well.",'game/session.gd',109,117,[('Paused','Player disabled'),('Resume','Reset the pending jump input')],[('disables',112,'Stop player updates'),('clears',117,'Discard buffered jump request')])
result(b,'Pause, resume, restart, and menu',"Escape pauses the jump, Enter resumes, and R restarts. The recording also exercises a simulated focus-loss event and a return to the menu. Those are scripted checks, not a student playtest. Repeat the meaningful cases yourself after the extension. Recovery and navigation belong to the game, not just the happy path to the flag.",'Normal Input events demonstrate pause/resume/restart/menu; focus loss is explicitly simulated.',take='pause')
board('Tests are evidence with a scope',"The starter includes mechanical tests, keyboard-event tests, a route helper, and a staged screenshot helper. Some tests set up internal state; a passing report is not the same as a human playing. Keep the baseline checks, add checks for your new landings and relocated finish, and update route fixtures when the geometry changes. Never delete a useful assertion merely to get green output.",[
 ['Automated','Mechanics + keyboard-event checks'],['Recorded','Scripted normal-input gameplay'],['Still required','Your own playtest of the extension']],
 'Test scripts live in godot/tests/ · staged captures ≠ played routes')
board('Predict, inspect, and revise once',"Write your change brief before prompting. Predict at least two ways the work might fail, such as a misleading silhouette or a camera that hides the next landing. Build one change, play it, inspect the cause, and make one documented revision. Keep the first failed attempt in Frictional. An honest struggle log is evidence of learning, not a contest to look effortless.",[
 ['CHANGE-BRIEF.md','Intent + invariants + two failure predictions'],['TEST-REPORT.md','Observed result + evidence + limitations'],['FRICTIONAL.md','Wrong turn → inspection → revision → retest']],
 'Predict → Build It → Use It → Ship It → Verify')
board('100 points, every ten days',"The assignment is one hundred points, with a ten-day cadence and the actual deadline in Canvas. Sixty points cover implementation and explanation: character, level, verification, and the required film. Ten cover the honest Frictional log, ten the matching GitHub and Canvas version, and twenty are the relative quartile after the whole group is reviewed. Meeting the other criteria does not guarantee those comparative points.",[
 ['60 · Implementation + explanation','Character 15 · level 20 · verification 15 · film 10'],['10 + 10 · Honest, reproducible work','Frictional 10 · GitHub / Canvas match 10'],['20 · Relative Quartile','Understanding, evidence, usability, communication']],
 'Canvas deadline controls · syllabus late penalty: 10% daily','rubric')
board('Ship source, a film, and the same version',"Use Brutalist's Godot walkthrough or game-development skill with the Walker bookends to make a landscape four-K explainer. Show your new character, both new landings, failure and recovery, and code followed by its result. Put text and source on GitHub; put videos and large media in the designated media storage and link them. Match the submitted commit in Canvas. Name the human and A I contributions and follow Professor Bear's linked A I policy.",[
 ['GitHub','Code + brief + tests + Frictional + SOURCES.md'],['Media storage','4K film + linked build evidence · no MP3/MP4 in Git'],['Canvas','Matching source ZIP + exact submitted commit + film link']],
 'AI policy: youtu.be/8Ut0Cdl6vMw · text files above 25 MB also belong in media storage')
add('The verdict',"The verdict: do not submit a changed screenshot. Submit a changed, playable system whose behavior you can explain. The A I can draft code, tests, art, and narration. You choose the goal, inspect the evidence, judge whether the result serves the player, and defend the submission. Production polish helps communication; it cannot replace a correct game or an honest explanation.",'ClaudeVerdictArtifact',{'artifactTitle':'Assignment 1 · verdict','artifactHeading':'A change you can defend','artifactLines':['A recognizable new character.','Two new jump landings and a relocated finish.','Code → visible result → evidence → revision.','AI helps produce. You inspect, judge, and explain.']})
prompt='Please inspect Walker Jumpman.\nPropose a distinct character and two new landings.\nPreserve movement; list tests before editing.'
add('Your turn',"Your turn. Please inspect Walker Jumpman. Propose a distinct character and two new landings. Preserve movement; list tests before editing. Use that prompt in Claude Code with the course's Walker context, then review the plan before accepting changes. Keep your predictions, play the extension yourself, and explain one revision the evidence made you choose. Liam, in for Professor Bear.",'ClaudeComposerAsk',composer(prompt,'Your Turn · review the plan before editing'))
add('Regular outro','', 'ClaudeTitleOutro',{'title':TITLE,'slug':SLUG})
save('beat_sheet.json',{'metadata':{'slug':SLUG,'title':TITLE,'persona':'Liam','palette':'claude','engine':'kokoro','voice':'am_onyx','voice_kokoro':'am_onyx','fps':30,'width':3840,'height':2160,'aspect_ratio':'16:9','caption_policy':'SRT sidecar; no burned captions','fit':'pad','skill':'godot-gamedev','modifier':'walker','human_review_approved':False,'authorization':'User requested a combined Assignment 1 film for the CSYE playlist. Local review master; no publication or replacement of existing videos.'},'beats':beats})
# Whole-source coverage is retained without pretending this concise assignment
# walkthrough explains every helper line in detail.
components=[{'id':'gameplay','files':['features/player/player.gd','features/player/tuning.gd','game/session.gd','levels/first_steps.json','ui/hud.gd'],'beat_ids':[b['beat_id'] for b in beats[6:23]],'explanation':'Character, physics, level, hazards, camera, HUD and recovery are traced from source to observable consequences.'},
 {'id':'startup','files':['project.godot','game/main.tscn'],'beat_ids':['B04'],'explanation':'Project selects the main scene; session creates runtime world. Existing file is imported, not an empty scene.'},
 {'id':'test-support','files':['tests/test_game.gd','tests/test_keyboard.gd','tests/route_driver.gd','tests/capture_game.gd'],'beat_ids':['B23'],'explanation':'Explains mechanical and keyboard checks, route fixtures and staged screenshot limitations without representing fixtures as human play.'}]
files=[]; exclusions=[]
for p in sorted((GAME/'godot').rglob('*')):
    if not p.is_file() or '.godot' in p.parts or p.suffix=='.uid':continue
    rel=p.relative_to(GAME/'godot').as_posix();ids=[c['id'] for c in components if rel in c['files']]
    if ids:files.append({'path':rel,'sha256':sha(p),'role':'test/support' if rel.startswith('tests/') else 'runtime/configuration','component_ids':ids})
    else:exclusions.append({'path':rel,'reason':'Non-runtime project metadata; inventoried, not a gameplay component.'})
save('gamedev-evidence.json',{'schema_version':1,'teaching_contract':'code-then-result-v1','files':files,'exclusions':exclusions,'components':components,'excerpts':excerpts,'code_result_pairs':pairs})
(ROOT/'SCRIPT.md').write_text('# '+TITLE+'\n\nLiam persona. New combined film; existing public films preserved.\n\n'+'\n'.join('## '+b['beat_id']+' — '+b['heading']+'\n\n'+(b['narration_text'] or '[Regular stock outro jingle only.]')+'\n' for b in beats))
(ROOT/'SHOTLIST.md').write_text('# Shot list\n\nEvery source excerpt is immediately followed by actual media evidence.\n\n'+'\n'.join('- '+b['beat_id']+' · '+b['heading']+' · '+b['shot']['type'] for b in beats)+'\n')
(ROOT/'PROMPTS.md').write_text('# Authoring provenance\n\nUser asked to combine setup, walkthrough and gamedev for Assignment 1, explicitly alternating source and visual consequence. Opening and Your Turn are suggested prompts, not historical Claude chats. No generated image/video service used.\n')
(ROOT/'FACTCHECK.md').write_text('# Source and claim audit\n\nSource audit PASS. Course requirements follow evidence/assignment.html. Code is exact and matched by file hash and line number. Gameplay is identified same-build archival Godot footage using scripted normal Input events, not a human playtest. Art previews are staged real engine drawings. No new student character or extension is claimed. Existing tests are re-run in an isolated copy. Public Walker is legacy Unity-oriented reference material; the standalone Godot starter does not need an invented Walker CLI. Final visual/audio inspection pending.\n')
(ROOT/'SOURCES.md').write_text('# Sources and contributions\n\n- Course Assignment 1: evidence/assignment.html (original Canvas HTML preserved).\n- [Walker](https://github.com/nikbearbrown/walker): main README checked September 10, 2026; legacy Unity language disclosed.\n- [Walker Jumpman](https://github.com/nikbearbrown/walker-jumpman): standalone GDScript starter; local source-build and capture hashes retained.\n- [Godot macOS download](https://godotengine.org/download/macos/): regular engine demonstrated; reconstructed UI, not live recording.\n- [NEU Claude access](https://claude.northeastern.edu/): course-provided account expectation, no promised separate API allowance.\n- [Professor Bear AI policy](https://youtu.be/8Ut0Cdl6vMw?si=9w3aEpt1ZyAR4Kiz).\n- Toolkit: brutalist.art; reused Godot and Claude scenes, local AssignmentBoard and engine-preview layout. Kokoro am_onyx (Liam), not a recording of Professor Bear. Fonts and stock outro retained from toolkit.\n\nHuman: course goals, rules, starter and requested pedagogical correction. AI: script, source inspection, scene construction, build, narration, automated checks. Human film review remains pending. No paid generation or posting performed.\n')
print(json.dumps({'reel':str(ROOT),'beats':len(beats),'code_result_pairs':len(pairs),'words':sum(len(b['narration_text'].split()) for b in beats)},indent=2))
